baseURL = "https://suguni.github.io/"

languageCode = "ko"

title = "따라쟁이"

theme = "paperback"

# googleAnalytics = "UA-123-45"

[params]

# your name to display by the copyright sign
AuthorName = "suguni"

# tagline to show beneath homepage h1
Tagline = "안녕, 세상!"

# number of posts to show on index
HomepagePosts = 20

# default: undefined
GithubUsername = "suguni"

# default: undefined
TwitterUsername = "suguni"

# default: undefined
# LinkedInUsername = "damiencaselli"
